name: Lingmo OS Autobuild

permissions: write-all

on:
  push:
    branches: [ main ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: debian:12

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        apt-get update
        apt-get install -y wget dpkg curl extra-cmake-modules libkf5configwidgets-dev libkf5i18n-dev libkf5config-dev libkf5iconthemes-dev libkf5guiaddons-dev rsync autoconf automake

    - name: Install GitHub CLI
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        apt-get update
        apt-get install -y gh

    - name: Install Lingmo build tool
      run: |
        wget https://packages.lingmo.org/lingmo/pool/main/l/lingmo-pkgbuild/lingmo-pkgbuild_0.1.0-1~lingmo1_amd64.deb
        wget https://packages.lingmo.org/lingmo/pool/main/libl/liblingmo/liblingmo_1.10.1_amd64.deb
        apt install -y ./*.deb
        apt-get install -f

    - name: Create packages
      run: |
        apt build-dep apt
        mkdir -p buildpkg mkdir -p buildpkg_tp
        autoreconf -fiv
        ./configure
        make pkg_all

    - name: Move files and compress directory
      run: |
        mv pkg_out release

    - name: Create release tarball
      run: |
        tar -cJf release.tar.xz -C release .

    - name: Set Release Tag
      id: set_tag
      run: echo "TAG_NAME=3.0.0-rc9-build-$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: Release ${{ env.TAG_NAME }}
        draft: false
        prerelease: false

    - name: Upload release directory files
      run: |
        for file in release/*; do
          if [ -f "$file" ]; then
            echo "Uploading $file"
            curl -XPOST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                 -H "Content-Type: $(file --mime-type -b $file)" \
                 --data-binary @"$file" \
                 "${{ steps.create_release.outputs.upload_url }}?name=$(basename "$file")"
          fi
        done

    - name: Upload release tarball
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: release.tar.xz
        asset_name: release.tar.xz
        asset_content_type: application/x-xz